name: Send Nairaland Top Stories

on:
  workflow_dispatch:      # run manually from the Actions tab
  push:
    branches: [ main ]    # sanity check on each push
  schedule:
    - cron: "1 2 * * *"   # 07:00 UTC daily ≈ 08:00 Africa/Lagos

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          FROM = os.environ.get("FROM_EMAIL")
          TO = os.environ.get("TO_EMAIL")
          PASS = os.environ.get("EMAIL_PASS")
        run: |
          python automatic_email.py
